name: CI
on:
  push:
    paths:
    # Build
    - 'Makefile'
    - 'aqua.yaml'
    # GoReleaser
    - '.goreleaser.yml'
    # GitHub Actions
    - '.github/workflows/ci.yml'
    # Go
    - '**.go'
    - 'go.mod'
    - 'go.sum'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu
        - macos
        # Activate when the following pull requests are merged
        # https://github.com/aquaproj/aqua-installer/pull/114
        # - windows
        go:
        - '1.17'
        - '1.18'
    env:
      RELEASE_OS: ubuntu
      RELEASE_GO_VERSION: '1.18'
    runs-on: ${{ matrix.os }}-latest
    name: Go ${{ matrix.go }} (${{ matrix.os }})
    defaults:
      run:
        shell: bash
    steps:
    ################################################################################
    # Checkout
    ################################################################################
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ startsWith(github.ref, 'refs/tags/') && '0' || '1' }}
    ################################################################################
    # Setup
    ################################################################################
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@v1.0.0
      with:
        aqua_version: v1.14.1
    ################################################################################
    # Cache
    ################################################################################
    - name: Cache Directory
      id: cache-dir
      run: |
        GOCACHE="$(go env GOCACHE)"
        GOMODCACHE="$(go env GOMODCACHE)"
        test -z "${GOCACHE}" && GOCACHE="${HOME}/.cache/go-build"
        test -z "${GOMODCACHE}" && GOMODCACHE="$(go env GOPATH)/pkg/mod"
        test -z "${AQUA_ROOT_DIR}" && AQUA_ROOT_DIR="${HOME}/.local/share/aquaproj-aqua"
        echo "::set-output name=go-build::${GOCACHE}"
        echo "::set-output name=go-mod::${GOMODCACHE}"
        echo "::set-output name=aqua::${AQUA_ROOT_DIR}"
        echo "GOCACHE=${GOCACHE}" >> $GITHUB_ENV
        echo "GOMODCACHE=${GOMODCACHE}" >> $GITHUB_ENV
        echo "AQUA_ROOT_DIR=${AQUA_ROOT_DIR}" >> $GITHUB_ENV
    - name: Go Build Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.cache-dir.outputs.go-build }}
        key: ${{ matrix.os }}-go-${{ matrix.go }}-build-${{ hashFiles('**/go.sum') }}-${{ hashFiles('.github/actions-cache-version') }}
    - name: Go Mod Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.cache-dir.outputs.go-mod }}
        key: ${{ matrix.os }}-go-${{ matrix.go }}-mod-${{ hashFiles('**/go.sum') }}-${{ hashFiles('.github/actions-cache-version') }}
    - name: Aqua Tools Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.cache-dir.outputs.aqua }}
        key: ${{ matrix.os }}-aqua-tools-${{ hashFiles('**/aqua.yaml') }}-${{ hashFiles('.github/actions-cache-version') }}
    ################################################################################
    # Go
    ################################################################################
    - name: Go Mod Download
      run: go mod download
    - name: Go Mod Tidy
      run: go mod tidy
    - name: Go Tools
      run: make tools
    - name: Go Generate
      run: make generate
    - name: Go Vet
      run: make vet
    - name: Go Lint
      run: make lint
    - name: Go Test
      run: make test
    - name: Go Build
      run: make build
    ################################################################################
    # GoReleaser
    ################################################################################
    - name: GoReleaser (${{ startsWith(github.ref, 'refs/tags/') && 'Release' || 'Snapshot' }})
      if: ${{ matrix.os == env.RELEASE_OS && matrix.go == env.RELEASE_GO_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        make ${{ startsWith(github.ref, 'refs/tags/') && 'release' || 'snapshot' }}
    ################################################################################
    # Artifact
    ################################################################################
    - name: Artifacts
      if: ${{ matrix.os == env.RELEASE_OS && matrix.go == env.RELEASE_GO_VERSION }}
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: |
          dist/*.tar.gz
          dist/*.zip
          dist/*.txt
